version: '3.3'
services:
  app:
    image: isabelnzioka/javaeeimage:v16
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: Nzioka15*
      MYSQL_DATABASE: tours
