---
- name: Tour-application deployment
  hosts: all
  become: true
  tasks:
    - name: Recursively change ownership
      file:
        path: /home/isabel/Tours/
        state: directory
        recurse: yes
        owner: isabel
      become: true

    - name: Copy Docker Compose File
      copy:
        src: ./docker-compose.yml
        dest: /home/isabel/Tours/docker-compose.yml

    - name: Run Docker Container
      command: docker-compose -f /home/isabel/Tours/docker-compose.yml up -d