version: '3.3'
services:

  db:
    image: mysql:latest
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: Nzioka15*
      MYSQL_DATABASE: tours


  app:
    image: isabelnzioka/toursystem:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_HOST_URL: jdbc:mysql://db:3306/tours
      MYSQL_USER: root
      MYSQL_USER_PASSWORD: Nzioka15*